/**
 * ChannelUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.discord;

import com.fasterxml.jackson.annotation.*;

public class ChannelUpdate {
    @JsonPropertyDescription("1-100 character channel name")
    private String name;
    @JsonPropertyDescription("base64 encoded icon")
    private String icon;

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("icon")
    public void setIcon(String icon) {
        this.icon = icon;
    }

    @JsonGetter("icon")
    public String getIcon() {
        return this.icon;
    }
}

