/**
 * Channel automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.discord;

import com.fasterxml.jackson.annotation.*;

public class Channel {
    private String id;
    private Integer type;
    private String guildId;
    private Integer position;
    private String name;
    private String topic;
    private Boolean nsfw;
    private String lastMessageId;
    private Integer bitrate;
    private Integer userLimit;
    private Integer rateLimitPerUser;
    private String icon;
    private String ownerId;
    private String applicationId;
    private Boolean managed;
    private String parentId;
    private String lastPinTimestamp;
    private String rtcRegion;
    private Integer videoQualityMode;
    private Integer messageCount;
    private Integer memberCount;
    private Integer defaultAutoArchiveDuration;
    private String permissions;
    private Integer flags;
    private Integer totalMessageSent;
    private Integer defaultSortOrder;
    private Integer defaultForumLayout;

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("type")
    public void setType(Integer type) {
        this.type = type;
    }

    @JsonGetter("type")
    public Integer getType() {
        return this.type;
    }

    @JsonSetter("guild_id")
    public void setGuildId(String guildId) {
        this.guildId = guildId;
    }

    @JsonGetter("guild_id")
    public String getGuildId() {
        return this.guildId;
    }

    @JsonSetter("position")
    public void setPosition(Integer position) {
        this.position = position;
    }

    @JsonGetter("position")
    public Integer getPosition() {
        return this.position;
    }

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("topic")
    public void setTopic(String topic) {
        this.topic = topic;
    }

    @JsonGetter("topic")
    public String getTopic() {
        return this.topic;
    }

    @JsonSetter("nsfw")
    public void setNsfw(Boolean nsfw) {
        this.nsfw = nsfw;
    }

    @JsonGetter("nsfw")
    public Boolean getNsfw() {
        return this.nsfw;
    }

    @JsonSetter("last_message_id")
    public void setLastMessageId(String lastMessageId) {
        this.lastMessageId = lastMessageId;
    }

    @JsonGetter("last_message_id")
    public String getLastMessageId() {
        return this.lastMessageId;
    }

    @JsonSetter("bitrate")
    public void setBitrate(Integer bitrate) {
        this.bitrate = bitrate;
    }

    @JsonGetter("bitrate")
    public Integer getBitrate() {
        return this.bitrate;
    }

    @JsonSetter("user_limit")
    public void setUserLimit(Integer userLimit) {
        this.userLimit = userLimit;
    }

    @JsonGetter("user_limit")
    public Integer getUserLimit() {
        return this.userLimit;
    }

    @JsonSetter("rate_limit_per_user")
    public void setRateLimitPerUser(Integer rateLimitPerUser) {
        this.rateLimitPerUser = rateLimitPerUser;
    }

    @JsonGetter("rate_limit_per_user")
    public Integer getRateLimitPerUser() {
        return this.rateLimitPerUser;
    }

    @JsonSetter("icon")
    public void setIcon(String icon) {
        this.icon = icon;
    }

    @JsonGetter("icon")
    public String getIcon() {
        return this.icon;
    }

    @JsonSetter("owner_id")
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    @JsonGetter("owner_id")
    public String getOwnerId() {
        return this.ownerId;
    }

    @JsonSetter("application_id")
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    @JsonGetter("application_id")
    public String getApplicationId() {
        return this.applicationId;
    }

    @JsonSetter("managed")
    public void setManaged(Boolean managed) {
        this.managed = managed;
    }

    @JsonGetter("managed")
    public Boolean getManaged() {
        return this.managed;
    }

    @JsonSetter("parent_id")
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    @JsonGetter("parent_id")
    public String getParentId() {
        return this.parentId;
    }

    @JsonSetter("last_pin_timestamp")
    public void setLastPinTimestamp(String lastPinTimestamp) {
        this.lastPinTimestamp = lastPinTimestamp;
    }

    @JsonGetter("last_pin_timestamp")
    public String getLastPinTimestamp() {
        return this.lastPinTimestamp;
    }

    @JsonSetter("rtc_region")
    public void setRtcRegion(String rtcRegion) {
        this.rtcRegion = rtcRegion;
    }

    @JsonGetter("rtc_region")
    public String getRtcRegion() {
        return this.rtcRegion;
    }

    @JsonSetter("video_quality_mode")
    public void setVideoQualityMode(Integer videoQualityMode) {
        this.videoQualityMode = videoQualityMode;
    }

    @JsonGetter("video_quality_mode")
    public Integer getVideoQualityMode() {
        return this.videoQualityMode;
    }

    @JsonSetter("message_count")
    public void setMessageCount(Integer messageCount) {
        this.messageCount = messageCount;
    }

    @JsonGetter("message_count")
    public Integer getMessageCount() {
        return this.messageCount;
    }

    @JsonSetter("member_count")
    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    @JsonGetter("member_count")
    public Integer getMemberCount() {
        return this.memberCount;
    }

    @JsonSetter("default_auto_archive_duration")
    public void setDefaultAutoArchiveDuration(Integer defaultAutoArchiveDuration) {
        this.defaultAutoArchiveDuration = defaultAutoArchiveDuration;
    }

    @JsonGetter("default_auto_archive_duration")
    public Integer getDefaultAutoArchiveDuration() {
        return this.defaultAutoArchiveDuration;
    }

    @JsonSetter("permissions")
    public void setPermissions(String permissions) {
        this.permissions = permissions;
    }

    @JsonGetter("permissions")
    public String getPermissions() {
        return this.permissions;
    }

    @JsonSetter("flags")
    public void setFlags(Integer flags) {
        this.flags = flags;
    }

    @JsonGetter("flags")
    public Integer getFlags() {
        return this.flags;
    }

    @JsonSetter("total_message_sent")
    public void setTotalMessageSent(Integer totalMessageSent) {
        this.totalMessageSent = totalMessageSent;
    }

    @JsonGetter("total_message_sent")
    public Integer getTotalMessageSent() {
        return this.totalMessageSent;
    }

    @JsonSetter("default_sort_order")
    public void setDefaultSortOrder(Integer defaultSortOrder) {
        this.defaultSortOrder = defaultSortOrder;
    }

    @JsonGetter("default_sort_order")
    public Integer getDefaultSortOrder() {
        return this.defaultSortOrder;
    }

    @JsonSetter("default_forum_layout")
    public void setDefaultForumLayout(Integer defaultForumLayout) {
        this.defaultForumLayout = defaultForumLayout;
    }

    @JsonGetter("default_forum_layout")
    public Integer getDefaultForumLayout() {
        return this.defaultForumLayout;
    }
}

