/**
 * ChannelInvite automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.discord;

import com.fasterxml.jackson.annotation.*;

public class ChannelInvite {
    private Integer maxAge;
    private Integer maxUses;
    private Boolean temporary;
    private Boolean unique;
    private Integer targetType;
    private String targetUserId;
    private String targetApplicationId;

    @JsonSetter("max_age")
    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    @JsonGetter("max_age")
    public Integer getMaxAge() {
        return this.maxAge;
    }

    @JsonSetter("max_uses")
    public void setMaxUses(Integer maxUses) {
        this.maxUses = maxUses;
    }

    @JsonGetter("max_uses")
    public Integer getMaxUses() {
        return this.maxUses;
    }

    @JsonSetter("temporary")
    public void setTemporary(Boolean temporary) {
        this.temporary = temporary;
    }

    @JsonGetter("temporary")
    public Boolean getTemporary() {
        return this.temporary;
    }

    @JsonSetter("unique")
    public void setUnique(Boolean unique) {
        this.unique = unique;
    }

    @JsonGetter("unique")
    public Boolean getUnique() {
        return this.unique;
    }

    @JsonSetter("target_type")
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    @JsonGetter("target_type")
    public Integer getTargetType() {
        return this.targetType;
    }

    @JsonSetter("target_user_id")
    public void setTargetUserId(String targetUserId) {
        this.targetUserId = targetUserId;
    }

    @JsonGetter("target_user_id")
    public String getTargetUserId() {
        return this.targetUserId;
    }

    @JsonSetter("target_application_id")
    public void setTargetApplicationId(String targetApplicationId) {
        this.targetApplicationId = targetApplicationId;
    }

    @JsonGetter("target_application_id")
    public String getTargetApplicationId() {
        return this.targetApplicationId;
    }
}

