/**
 * MessageAllowedMentions automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.discord;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class MessageAllowedMentions {
    private java.util.List<String> parse;
    private java.util.List<String> roles;
    private java.util.List<String> users;
    private Boolean repliedUser;
    @JsonSetter("parse")
    public void setParse(java.util.List<String> parse) {
        this.parse = parse;
    }
    @JsonGetter("parse")
    public java.util.List<String> getParse() {
        return this.parse;
    }
    @JsonSetter("roles")
    public void setRoles(java.util.List<String> roles) {
        this.roles = roles;
    }
    @JsonGetter("roles")
    public java.util.List<String> getRoles() {
        return this.roles;
    }
    @JsonSetter("users")
    public void setUsers(java.util.List<String> users) {
        this.users = users;
    }
    @JsonGetter("users")
    public java.util.List<String> getUsers() {
        return this.users;
    }
    @JsonSetter("replied_user")
    public void setRepliedUser(Boolean repliedUser) {
        this.repliedUser = repliedUser;
    }
    @JsonGetter("replied_user")
    public Boolean getRepliedUser() {
        return this.repliedUser;
    }
}
