/**
 * User automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.discord;

import com.fasterxml.jackson.annotation.*;

public class User {
    private String id;
    private String username;
    private String discriminator;
    private String globalName;
    private String avatar;
    private Boolean bot;
    private Boolean system;
    private Boolean mfaEnabled;
    private String banner;
    private Integer accentColor;
    private String locale;
    private Boolean verified;
    private String email;
    private Integer flags;
    private Integer premiumType;
    private Integer publicFlags;

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    @JsonGetter("username")
    public String getUsername() {
        return this.username;
    }

    @JsonSetter("discriminator")
    public void setDiscriminator(String discriminator) {
        this.discriminator = discriminator;
    }

    @JsonGetter("discriminator")
    public String getDiscriminator() {
        return this.discriminator;
    }

    @JsonSetter("global_name")
    public void setGlobalName(String globalName) {
        this.globalName = globalName;
    }

    @JsonGetter("global_name")
    public String getGlobalName() {
        return this.globalName;
    }

    @JsonSetter("avatar")
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    @JsonGetter("avatar")
    public String getAvatar() {
        return this.avatar;
    }

    @JsonSetter("bot")
    public void setBot(Boolean bot) {
        this.bot = bot;
    }

    @JsonGetter("bot")
    public Boolean getBot() {
        return this.bot;
    }

    @JsonSetter("system")
    public void setSystem(Boolean system) {
        this.system = system;
    }

    @JsonGetter("system")
    public Boolean getSystem() {
        return this.system;
    }

    @JsonSetter("mfa_enabled")
    public void setMfaEnabled(Boolean mfaEnabled) {
        this.mfaEnabled = mfaEnabled;
    }

    @JsonGetter("mfa_enabled")
    public Boolean getMfaEnabled() {
        return this.mfaEnabled;
    }

    @JsonSetter("banner")
    public void setBanner(String banner) {
        this.banner = banner;
    }

    @JsonGetter("banner")
    public String getBanner() {
        return this.banner;
    }

    @JsonSetter("accent_color")
    public void setAccentColor(Integer accentColor) {
        this.accentColor = accentColor;
    }

    @JsonGetter("accent_color")
    public Integer getAccentColor() {
        return this.accentColor;
    }

    @JsonSetter("locale")
    public void setLocale(String locale) {
        this.locale = locale;
    }

    @JsonGetter("locale")
    public String getLocale() {
        return this.locale;
    }

    @JsonSetter("verified")
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    @JsonGetter("verified")
    public Boolean getVerified() {
        return this.verified;
    }

    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    @JsonGetter("email")
    public String getEmail() {
        return this.email;
    }

    @JsonSetter("flags")
    public void setFlags(Integer flags) {
        this.flags = flags;
    }

    @JsonGetter("flags")
    public Integer getFlags() {
        return this.flags;
    }

    @JsonSetter("premium_type")
    public void setPremiumType(Integer premiumType) {
        this.premiumType = premiumType;
    }

    @JsonGetter("premium_type")
    public Integer getPremiumType() {
        return this.premiumType;
    }

    @JsonSetter("public_flags")
    public void setPublicFlags(Integer publicFlags) {
        this.publicFlags = publicFlags;
    }

    @JsonGetter("public_flags")
    public Integer getPublicFlags() {
        return this.publicFlags;
    }
}

