/**
 * MessageAllowedMentions automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.discord;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class MessageAllowedMentions {
    private List<String> parse;
    private List<String> roles;
    private List<String> users;
    private boolean repliedUser;
    @JsonSetter("parse")
    public void setParse(List<String> parse) {
        this.parse = parse;
    }
    @JsonGetter("parse")
    public List<String> getParse() {
        return this.parse;
    }
    @JsonSetter("roles")
    public void setRoles(List<String> roles) {
        this.roles = roles;
    }
    @JsonGetter("roles")
    public List<String> getRoles() {
        return this.roles;
    }
    @JsonSetter("users")
    public void setUsers(List<String> users) {
        this.users = users;
    }
    @JsonGetter("users")
    public List<String> getUsers() {
        return this.users;
    }
    @JsonSetter("replied_user")
    public void setRepliedUser(boolean repliedUser) {
        this.repliedUser = repliedUser;
    }
    @JsonGetter("replied_user")
    public boolean getRepliedUser() {
        return this.repliedUser;
    }
}
